### ISSUE TITLE
Getting an error in Gmail when importing the latest mailFilters.xml file

### ISSUE THREAD

**Issue by JasonD94** [jceloria/recruiter-spam#7]
The error message says:

mailFilters.xml:1:40: Error parsing file: The markup in the document preceding the root element must be well-formed.

Looks like a popup:

![image](https://user-images.githubusercontent.com/7584563/132901861-46b6d746-096b-4ea4-989c-b53b6e2cbae8.png)

I had some issues importing the latest CSV file as well, but that was one of the email domains being invalided. Once I removed it, seems like all was well.

**Comment by jceloria** [comment]
Is this still an issue for you? I just imported all 211 w/out issue.

**Comment by JasonD94** [comment]
Might have been an issue with line endings. I'm on Windows 10, seems like my EOL was set to Windows style vs Unix. Switching this in Notepad++ for list.txt got me a valid filter file for Gmail using the bash script!

The powershell script might not be working for gmail style filters, but I only use that to generate CSV files for my custom domain that only accepts CSV files.

**Comment by JasonD94** [comment]
Might be something to do with encoding in the PowerShell script.

Bash script filter file (works with Gmail):
```
$ file mailFilters.xml
mailFilters.xml: XML 1.0 document, ASCII text
```

PowerShell script (doesn't work with Gmail, and is basically identical except for file size but has one extra entry at the end that the bash script missed...):
```
$ file mailFilters2.xml
mailFilters2.xml: XML 1.0 document, Unicode text, UTF-16, little-endian text
```

**Comment by jceloria** [comment]
This repository was meant for gmail filters, closing.
